FROM  docker.elastic.co/elastic-agent/elastic-agent:9.2.4
COPY elastic-agent.yml /usr/share/elastic-agent/elastic-agent.yml
USER root



# FROM docker.elastic.co/elasticsearch/elasticsearch:9.2.3
# RUN elasticsearch-plugin install --batch ingest-geoip

# USER elasticsearch 
