# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: kibana-sa
#   namespace: eck
#   annotations: {}
# imagePullSecrets:
#   - name: private-registry
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: elasticsearch-sa
#   namespace: eck
# imagePullSecrets:
#   - name: private-registry
# ---

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: eck
spec:
  version:  9.2.3
  auth:
    fileRealm:
      - secretName:  elastic-custom-users
  #   roles:
  #     - secretName: tracy-roles
  nodeSets: 
  - name: master
    count: 1
    config:
      index.store.type: mmapfs
      node.roles: ["master", "remote_cluster_client"]
      node.store.allow_mmap: true
      xpack.ml.enabled: false
      ## Below enabled for observability
      # xpack.security.authcbasic.enabled: true
      # xpack.security.enabled: true
      # xpack.security.auth.apiKey.enabled: true
      # xpack.security.authcremoteClusterClient.enabled: true

    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          resources:
            requests:
              storage: 10Gi
          accessModes:
            - ReadWriteOnce
    podTemplate:
      metadata:
        annotations:
          prometheus.istio.io/merge-metrics: "false"
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
      spec:
        affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: reserved
                    operator: In
                    values:
                    - elastic-master
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
        serviceAccountName:  elasticsearch-sa
        initContainers:
          - name: install-plugins
            command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin install --batch analysis-icu
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms1500m -Xmx1500m"
            resources:
              limits:
                cpu: 4
                memory: 4Gi
              requests:
                cpu: 4
                memory: 4Gi
            lifecycle:
              {}
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities:
                drop:
                - ALL
  - name: data
    count: 1
    config:
      index.store.type: mmapfs
      node.roles: ["data", "ingest", "remote_cluster_client"]
      node.store.allow_mmap: true
      xpack.ml.enabled: false
      ## Below enabled for observability
      # xpack.security.enabled: true
      # xpack.security.auth.apiKey.enabled: true
      # xpack.security.auth.basic.enabled: true
      # xpack.security.auth.remoteClusterClient.enabled: true

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        resources:
          requests:
            storage: 10Gi
        accessModes:
        - ReadWriteOnce
    podTemplate:
      metadata:
        annotations:
          prometheus.istio.io/merge-metrics: "false"
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
      spec:
        affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: reserved
                    operator: In
                    values:
                    - elastic-master
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
        serviceAccountName:  elasticsearch-sa
        initContainers:
          - name: install-plugins
            command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin install --batch analysis-icu
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms1500m -Xmx1500m"
            resources:
              limits:
                cpu: 4
                memory: 4Gi
              requests:
                cpu: 4
                memory: 4Gi
            lifecycle:
              {}
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities:
                drop:
                - ALL
  http:
    tls:
      certificate:
        secretName: elast-tls-certs 
    service:
      spec:
        ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 9200
          - name: http
            port: 9200 
            protocol: TCP
            targetPort: 9200

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: eck
spec:
  version: '9.2.3'
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: eck
  secureSettings:
  - secretName: kibana-encryption-keys
  config:
    server.publicBaseUrl: "https://kibana.fredgentech.com"
    xpack.security.audit.enabled: true
    xpack.fleet.enabled: true
    xpack.security.audit.appender:
      type: file
      fileName: /var/log/kibana/audit.log
      layout:
        type: json
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        ports:
          - name: http
            port: 5601
            protocol: TCP
            targetPort: 5601
  podTemplate:
    spec:
      nodeName: prod-node-03
      volumes: 
      - name: kibana-logs
        persistentVolumeClaim:
          claimName: kibana-data-pvc
        # emptyDir: {}
      serviceAccountName: kibana-sa
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      containers:
      - name: kibana
        env:
        - name: SERVER_BASEPATH
          value: "" 
        volumeMounts: 
        - name: kibana-logs
          mountPath: /var/log/kibana

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     common.k8s.elastic.co/type: kibana
#     kibana.k8s.elastic.co/name: kibana
#   name: kibana
#   namespace: eck
# spec:
#   ports:
#     - name: http
#       port: 5601
#       protocol: TCP
#       targetPort: 5601
#   selector:
#     common.k8s.elastic.co/type: kibana
#     kibana.k8s.elastic.co/name: kibana
#   type: ClusterIP

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: elastic-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     pv.kubernetes.io/bind-completed: "yes"
#     pv.kubernetes.io/bound-by-controller: "yes"
#   labels:
#     common.k8s.elastic.co/type: elasticsearch
#     elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
#     elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-data
#   name: elasticsearch-data-elasticsearch-es-data-0
#   namespace: eck
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: elastic-storage
#   volumeMode: Filesystem
#   volumeName: data-elasticsearch-es-data-pv

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-elasticsearch-es-data-pv
#   labels:
#     elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
#     type: local
# spec:
#   storageClassName: elastic-storage
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/usr/share/elasticsearch/data/es-data-0"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     pv.kubernetes.io/bind-completed: "yes"
#     pv.kubernetes.io/bound-by-controller: "yes"
#   labels:
#     common.k8s.elastic.co/type: elasticsearch
#     elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
#     elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-master
#   name: elasticsearch-data-elasticsearch-es-master-0
#   namespace: eck
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: elastic-storage # longhorn
#   volumeMode: Filesystem
#   volumeName: data-elasticsearch-es-master-pv

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-elasticsearch-es-master-pv
#   labels:
#     elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
#     type: local
# spec:
#   storageClassName: elastic-storage
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/usr/share/elasticsearch/data/es-master-0"

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: kibana-kb-pv
# spec:
#   storageClassName: elastic-storage
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/var/log/kibana/"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     pv.kubernetes.io/bind-completed: "yes"
#     pv.kubernetes.io/bound-by-controller: "yes"
#   name: kibana-data-pvc
#   namespace: eck
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: elastic-storage 
#   volumeMode: Filesystem
#   volumeName: kibana-kb-pv
