

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: eck
spec:
  version: 8.12.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          annotations:
            traffic.sidecar.istio.io/includeInboundPorts: "*"
            traffic.sidecar.istio.io/excludeOutboundPorts: "9300" 
            traffic.sidecar.istio.io/excludeInboundPorts: "9300"
        spec:
          automountServiceAccountToken: true
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: 4
                limits:
                  memory: 8Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  http:
    service:
      spec:
        ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 9200

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: eck
spec:
  version: 8.9.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: eck
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        ports:
          - name: http
            port: 5601
            protocol: TCP
            targetPort: 5601
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: SERVER_BASEPATH
            value: "" 

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kibana-vs
  namespace: eck
spec:
  gateways:
    - istio-system/general-gateway 
  hosts:
    - kibana.fredgentech.net
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kibana
            port:
              number: 5601
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elastic-vs
  namespace: eck
spec:
  gateways:
    - istio-system/general-gateway 
  hosts:
    - elastic.fredgentech.net
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: elatsearch-es-http
            port:
              number: 443
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-01-22T22:08:58Z'
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  name: kibana
  namespace: eck
spec:
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  type: ClusterIP