# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: elasticsearch-data-elasticsearch-es-default-0
#   namespace: eck
#   labels:
#     elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
#     type: local
# spec:
#   storageClassName: local-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elasticsearch-es-default-pv
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/elasticsearch/data"