# apiVersion: v1 
# kind: Secret
# metadata:
#   name: keycloak-externaldb
#   namespace: user-management
# immutable: true
# data: 
#    password: aHVpZmRvaXR5bG9ha3BkaGdkZmRhc3MyMzQK
  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: keycloak
  namespace: user-management
spec:
  gateways:
  - istio-system/general-gateway
  hosts:
  - 'keycloak.fredgentech.net'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak
        port:
          number: 80


  # admin-password: YWRtaW4=
  # database: a2V5Y2xvYWs=
  # db-password: YUhWcFptUnZhWFI1Ykc5aGEzQmthR2RrWm1SaGMzTXlNelFL
  # host: a2V5Y2xvYWsuY3hoZmFxc2V5MHVnLnVzLXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  # port: NTQzMg==
  # user: cG9zdGdyZXM=