apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: stigman
  name: stigman
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: stigman
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/mani-default: "true"
        io.kompose.service: stigman
    spec:
      # imagePullSecrets: 
      # - name: private-registry
      containers:
        - image: jmugu/stig-manager:1.0.0 #ghcr.io/asongent/stig-manager:1.0.0
          name: stigman
          resources: {}
          env:
            - name:  STIGMAN_CLASSIFICATION
              value: CUI

            - name:  STIGMAN_DB_HOST
              value: '192.168.1.73'

            - name:  STIGMAN_DB_PASSWORD
              value: YzNScFoyMWhibUZuWlhJSwo=
            - name: STIGMAN_DB_SCHEMA
              value: stigmanager

            - name:  STIGMAN_DB_USER
              value: stigman-admin

            - name:  STIGMAN_CLIENT_KEYCLOAK_CLIENTID
              value: stig-manager

            # - name:  STIGMAN_JWT_PRIVILEGES_CLAIM
            #   value: stig-manager

            - name:  STIGMAN_OIDC_PROVIDER
              value: https://keycloak.stack.fredgentech.net/auth/realms/stigman

            - name:  STIGMAN_CLIENT_OIDC_PROVIDER
              value: https://keycloak.stack.fredgentech.net/auth/realms/stigman
          
          ports:
            - containerPort: 54000
              name: http
              protocol: TCP
      restartPolicy: Always
