apiVersion: v1
kind: Secret
metadata:
  name: neuvector-creds
  namespaces: cipha-hub
type: Opaque
stringData:
  username: "admin"
  password: "yourpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-creds
  namespaces: cipha-hub
type: Opaque
stringData:
  username: "elastic"
  password: "yourpassword"
