apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
    path: argocd
    kustomize:
      version: v4.5.7
  destination: 
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true