# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kibana
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL:  https://github.com/asongent/gen.git
#     targetRevision: HEAD
#     path: elastic-search-anty-affinity/kibana
#     helm:
#       valueFiles:
#       - values.yaml
#   destination:
#     namespace: elastic
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# ---

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: elasticsearch
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL:  https://github.com/asongent/gen.git
#     targetRevision: HEAD
#     path: elastic-search-anty-affinity/elasticsearch
#     helm:
#       valueFiles:
#       - values.yaml
#   destination:
#     namespace: elastic
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: spark
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL:  https://github.com/asongent/gen.git
#     targetRevision: HEAD
#     path: elastic-search-anty-affinity/spark
#     helm:
#       valueFiles:
#       - values.yaml
#   destination:
#     namespace: spark
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
    path: elastic-search-anty-affinity/keycloak
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true