apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-resources
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: eso-resources
    kustomize:
      version: v5.2.1 
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true