apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-fleet
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
    path: eck
  destination:
    namespace: eck-fleet
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true