apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: user-management
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: keycloak-bit
    # kustomize:
    #   version: v4.5.7
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true