apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  destination:
    namespace: kiali
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: kiali
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true