apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
    path: neo4j
  destination:
    namespace:  neo4j
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true