apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets
  namespace: argocd
spec:
  destination:
    namespace: vault-test
    server: https://kubernetes.default.svc
  project: default
  source:
    # plugin:
    #   name: argocd-vault-plugin
    path: vault-secret
    repoURL:  https://github.com/asongent/gen.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
