
{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app:  {{ .Release.Name }}-mysql
    tier: {{ .Release.Name }}
{{- end }}