{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-prometheus-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{ include "policyreporter.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
    - port: 15020
      protocol: TCP
{{- end }}