
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-keycloak-mutate
  namespace: keycloak
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-keycloak-mutate-binding
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-keycloak-mutate
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno

--- 
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restart-statefulset-on-secret-change
  annotations:
    policies.kyverno.io/title: Restart StatefulSet On Secret Change
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: StatefulSet
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      If Secrets are mounted in ways which do not naturally allow updates to
      be live refreshed it may be necessary to modify a StatefulSet. This policy
      watches a Secret and if it changes will write an annotation
      to one or more target StatefulSets thus triggering a new rollout and thereby
      refreshing the referred Secret. It may be necessary to grant additional privileges
      to the Kyverno ServiceAccount, via one of the existing ClusterRoleBindings or a new
      one, so it can modify StatefulSets.
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
  - name: update-secret
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - keycloak-tls
          namespaces:
          - keycloak
    preconditions:
      all:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: Equals
        value: UPDATE
    context:
      - name: stsList
        apiCall:
          urlPath: "/apis/apps/v1/namespaces/keycloak/statefulsets"
          jmesPath: "items[?metadata.labels.\"app.kubernetes.io/instance\"=='keycloak']"
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: StatefulSet
          name: keycloak
          namespace: keycloak
      patchStrategicMerge:
        spec:
          template:
            metadata:
              annotations:
                ops.corp.com/triggerrestart: "{{request.object.metadata.resourceVersion}}"
