apiVersion: v1
kind: Secret
metadata:
  name: keycloak-env
  namespace: keycloak
type: Opaque
stringData:
  JAVA_OPTS_APPEND: "-Djgroups.dns.query=keycloak-headless"
  JAVA_TOOL_OPTIONS: "-Dcom.redhat.fips=false"
  KEYCLOAK_ADMIN: "nd-alfred"
  KEYCLOAK_ADMIN_PASSWORD: "Tracy2018"