apiVersion: v2
name: sonarqube
description: SonarQube offers Code Quality and Code Security analysis for up to 27 languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout your workflow.
type: application
version: 8.0.2-bb.1
appVersion: 9.9.2
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/docker-sonarqube
  - https://github.com/SonarSource/sonarqube
kubeVersion: '>= 1.19.0-0'
maintainers:
  - name: leo-geoffroy-sonarsource
    email: leo.geoffroy+helm@sonarsource.com
  - name: carminevassallo
    email: carmine.vassallo@sonarsource.com
  - name: jCOTINEAU
    email: jeremy.cotineau@sonarsource.com
annotations:
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fix missing `bitnami/minideb-extras` image during helm tests"
    - kind: changed
      description: "Update SonarQube to 9.9.2"
  artifacthub.io/containsSecurityUpdates: "false"
  bigbang.dev/applicationVersions: |
    - Sonarqube: 9.9.2-community
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:9.9.2-community
  helm.sh/images: |
    - name: sonarqube
      image: registry1.dso.mil/ironbank/big-bang/sonarqube-9:9.9.2-community
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
    - name: postgresql12
      condition: postgresql.enabled
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:12.16
dependencies:
- name: postgresql
  version: 8.6.4
  repository: file://./deps/postgresql
  condition: postgresql.enabled
- name: gluon
  version: "0.4.1"
  repository: "oci://registry1.dso.mil/bigbang"
