apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tls-sec
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secrets-source       
  target:
    name: keycloak-tls
    template:
      type: kubernetes.io/tls 
      metadata:
        labels:
          app.kubernetes.io/instance: keycloak
          app.kubernetes.io/name: keycloak  
  data:
  - secretKey: tls.crt
    remoteRef:
      key: /certificates/keycloak
      property: crt
  - secretKey: tls.key
    remoteRef:
      key: /certificates/keycloak
      property: key
      
  