apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secrets-source       
  target:
    name: database-credentials 
  data:
  - secretKey: username
    remoteRef:
      key: dev
      property: username
      
  - secretKey: password
    remoteRef:
      key: dev
      property: password

  - secretKey: port
    remoteRef:
      key: dev
      property: port

  - secretKey: db_url
    remoteRef:
      key: dev
      property: db_url
  # # metadataPolicy to fetch all the labels and annotations in JSON format
  # - secretKey: tags
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: database-credentials

  # # metadataPolicy to fetch all the labels in JSON format
  # - secretKey: labels
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: database-credentials
  #     property: labels

  # # metadataPolicy to fetch a specific label (dev) from the source secret
  # - secretKey: developer
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: database-credentials
  #     property: labels.dev