apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.version.v4.1.1_ksops: /custom-tools/kustomize
  kustomize.buildOptions.v4.1.1_ksops: "--enable-alpha-plugins"
  kustomize.buildOptions:           "--enable-alpha-plugins"
  kustomize.version.v5.2.1: /custom-tools/kustomize_5_2_1
  resource.compareoptions: |
    ignoreAggregatedRoles: true
  # ui.bannercontent: "Welcome To New Generation Technology!"
  timeout.reconciliation: 5s
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/0/failurePolicy
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /spec/scope
  # repositories: |
  #   - url:  https://github.com/asongent/gen.git
  #     sshPrivateKeySecret:
  #       name: private-repo 
  #       key: sshprivateKey
  # configManagementPlugins: |-
  #   - name: argocd-vault-plugin
  #     generate:
  #       command: ["argocd-vault-plugin"]
  #       args: ["generate", "./"]

