apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stig-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ include "stig-manager.name" . }}
