apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "stig-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]