apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
--- 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: general-gateway
  namespace: istio-system
  labels:
    app.kubernetes.io/instance: ingressgateway
    #app: ingressgateway
    istio: ingressgateway
    app: istio-ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    # Upgrade HTTP to HTTPS
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gateway-certs 


# --- 
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: seldon-gateway
#   namespace: istio-system
#   labels:
#     app.kubernetes.io/instance: ingressgateway
#     app: ingressgateway
#     istio: ingressgateway
# spec:
#   selector:
#     istio: ingressgateway # use istio default controller
#   servers:
#   - hosts:
#     - 'seldon-model.fredgentech.com'
#     port:
#       name: http
#       number: 80
#       protocol: HTTP
#     # Upgrade HTTP to HTTPS
#     tls:
#       httpsRedirect: true
#   - hosts:
#     - 'seldon-model.fredgentech.com'
#     port:
#       name: https
#       number: 443
#       protocol: HTTPS
#     tls:
#       mode: SIMPLE
#       credentialName: gateway-certs 




    
 