{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations: {{- toYaml .Values.ingress.annotations| nindent 10 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts: 
    - {{ .Values.ingress.host}}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: /
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              number: {{ .Values.ingress.service.port }}
{{- end }}