{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "stig-manager.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "stig-manager.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
{{- end }}