apiVersion: v1
kind: Service
metadata:
  name: {{ include "stig-manager.fullname" . }}
spec:
  type: {{ .Values.service.type}}
  selector:
    app: {{ include "stig-manager.name" . }}
  ports:
    {{- range .Values.service.ports }}
      - protocol: {{ .protocol }}
        port: {{ .port }}
        {{- if .targetPort }}
        targetPort: {{ .targetPort }}
        {{- end }}
    {{- end }}