apiVersion: v1
kind: Secret
metadata:
  name: sso-secret
  namespace: eck
type: Opaque
data:
  xpack.security.authc.realms.oidc.New%20Gen%20Tech.rp.client_secret: U1AzcFNGbWhUTElZbE81bHJtc0NpTnRwUzJEOVRxNks=
