apiVersion: v1
kind: Secret
metadata:
    name: sso-secret
    namespace: eck
type: Opaque
data:
    xpack.security.authc.realms.oidc.New%20Gen%20Tech.rp.client_secret: ENC[AES256_GCM,data:9LZQAHJRtWgk6kLcR+aHTqzEpF3Kj1LSDBB0MZjFENrERMEygjjwMfz7BGs=,iv:fdlgsKRN3kHm/ha6wB4astk7l+51FlVyx0qrPm7ErZA=,tag:Y4R8W1nWZf4Cn4Z3P2/Dnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcTQ2Rk5tbmdGR0Y4SjJ0
            VFVIZmc1OWM4UHJKS0VhTy9HeW5zNWt0UDJnCmZvd3p2S3l1OVl3RHRwSFVsS0h6
            RUFZSzlKMUkzcms2ZkpjVmxmb2JLU0UKLS0tIHRYeEdrZkU0ZFJTMU0rTXllazdR
            NTJ4b3F4c0JjMW4yUGN2dGMyZWZHaEkK4Cuumy6uTfg4gJ7CAsWvTW/seNhvjHnP
            BJHuOVvzTXnpNEW5ccQIt4m7WGNj1s4U+AtufuyYhFSryOKmdZiBsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-02T23:31:37Z"
    mac: ENC[AES256_GCM,data:k/DZ3RoeFeYvWu2rqVwYbqo3GT5Csb01vJVyLKY3HFrX435Wts6PPkzYzc9xiagXJd2LTAG3YSs14ErNHi6ZA5PNPpEi6bJMarniLY9HAwjg2/LGFmqnpRQtOyuRqiUrjHhGh6G4tEhK6Ska2jl+1ox6wbIXobYyWAm+2p0gMEQ=,iv:dITQm72dsnzE4A885U//ZxYEaMX/WywtmO77OWVVHKk=,tag:1qacOfFwxSxR4qjm2XBalg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
