apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qGH83g8StVA+rQINOJV1hbnJBIeU1kTaGI//H/UTMxSRKOJ+ASfUQ7tMmOWjtiXwjKYONgxAg+nv4hzaazT35pRhXcXAp3MAYpQy+uis5n13UrcetNrDlCj5fctjPtcJEGVAkC9spnzAHSjpEEw2O/alqCiVlt1GkR1sCybofL81X6D3JHU7o2pB//xpGWF6Hrcc85Tetf4mQfitJehEC/4FeHiIWPyg4OLZM614z+rR5xA4zwNnEUIkAQAk/k9WvPg8Bz8ga9Spg39lw+lc+XvXQ3MnX3ZCISCjMOfUDBI8gJOuu7qCEqpZJ8OMyRd0KdWTz8LegtO3J1xKkZtzVTCD8CHhvJSeHs44VHcjqGc=,iv:SdfGk/YP4aZunHh+AZ1Vd8a/qHzbRMgUxANP6pHhi4w=,tag:ADq6wLZLhAHhK+6XRQbDcg==,type:str]
kind: Secret
metadata:
    name: iron-bank
    namespace: sonarqube
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDF0amx1WUV5YTgybHhR
            UkRVS3BvVDJmWVZZTmY3UkNyNHZuUUROaWlFCkdVbjRIYWN3Rkp2c3c1SWFadXRN
            djliNXZiTEZsNm1qemdQVEtqbmVWU2cKLS0tIDRoZUFSRW81Tms2WnJtWVgwS0xH
            Q21zcnZNZnBLdE9kUGtXdzlkTjBTMnMK4rJc+oJyid9I1YI/gj7klX1SaWHIDV/7
            yQxYlEQspmCKSg4GbdA/buKic8cALPZDMBg98aNFeaFHs5rbvyjLFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T18:04:49Z"
    mac: ENC[AES256_GCM,data:lWlJDaddyFpS0bRlkcB3uFuUN5P45B/PBMZUG17lx0ovB4Zxlk2O/R3/y17yGV0RGszQgzLThX+Z/NOL5h+fqg1LL3pJ+r8Bto0NoCYQeSiOV4v10X/sT62wRki2m3JTkWjWIMwGr1QstiDxv+B21NEmkzKV85EclpW8FZJ+wXI=,iv:Vtl73b7dGKlrpRdSEhOfcFQ2NeTqs2bKX+YK3so2tfs=,tag:z5PznSkf6H+e4Cg3Z79uKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:urd85RC9l+oOWeoHeJPGjxjazEp6cU2hJLTK0WylIsO3a96SThBZ6nQl+fZb7OFaB39RXT+pAhcWLyDYCN2L9IEMe0WdjaSHdnlZT5tp9KvNpDpUNBt9Bt+1nGoKNsaVl/cShOxLV9PJjLr3dy2NzG0jIlzwhv+vXJggL6StrcJs9P6UpMr4pyWyjFaggGp+jY+62PycIILpdGtkit9VH7aFWrZ5hvy7ziTE1MQ4nrp+UogAXcsdJoxiYrwPpCiKPaLuqXcZJ0V+cEIvCjbGHlwMrFTe4v44Kp2swalJPNfnaytYgwQ3fIuGUHdGOxGRMJWKckBO3xFja+xzOWXuqlNenwjoIXAdF03i3EmXubY=,iv:qWkzoIZKiMALO7BAXgeNNeIZFRjEJBcP0GWb/P5hzVg=,tag:wT35N5tNbyznfkR8z6uG1A==,type:str]
kind: Secret
metadata:
    name: iron-bank
    namespace: gitlab
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDF0amx1WUV5YTgybHhR
            UkRVS3BvVDJmWVZZTmY3UkNyNHZuUUROaWlFCkdVbjRIYWN3Rkp2c3c1SWFadXRN
            djliNXZiTEZsNm1qemdQVEtqbmVWU2cKLS0tIDRoZUFSRW81Tms2WnJtWVgwS0xH
            Q21zcnZNZnBLdE9kUGtXdzlkTjBTMnMK4rJc+oJyid9I1YI/gj7klX1SaWHIDV/7
            yQxYlEQspmCKSg4GbdA/buKic8cALPZDMBg98aNFeaFHs5rbvyjLFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T18:04:49Z"
    mac: ENC[AES256_GCM,data:lWlJDaddyFpS0bRlkcB3uFuUN5P45B/PBMZUG17lx0ovB4Zxlk2O/R3/y17yGV0RGszQgzLThX+Z/NOL5h+fqg1LL3pJ+r8Bto0NoCYQeSiOV4v10X/sT62wRki2m3JTkWjWIMwGr1QstiDxv+B21NEmkzKV85EclpW8FZJ+wXI=,iv:Vtl73b7dGKlrpRdSEhOfcFQ2NeTqs2bKX+YK3so2tfs=,tag:z5PznSkf6H+e4Cg3Z79uKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:QA/jqh79tq5InleFRpiy/XAwnq3q4ft7fXN0Rvmu8SwHNC7Rnq1LqkqTh8SKEE5hRbRRWu7AmA7cqCWqIzh7fHPacap7f1uQIzo4oe8oYzyE3yvs1xbU6DshaxyCSMCHANaipR8/YrJ7hScZGAxRadH/s+m6tjDTY+if/nOdgLhOMyHF0NgSRqQzPvcHlczjnN5K1DfqcQOZmHEQlijQOF9NmYLgeKhxTASH/AaYkC3nSUcjlRo49YWpSfbKdvyKmF+kQ+XlOXvWTpzppPgHuJaJqwNNmQDuQSV7Y8XAupZziCTIx3R6jJChOcpY/isQp49FRLze3PIqLeghNL0vj05PvidaqLbBRWTwZsbhQqY=,iv:tLjbXbe5on432jEgalBa3Q66TJ6RJ1zlukYeKUovxeQ=,tag:JooPOXtuHe8cSYbQyg6Ngg==,type:str]
kind: Secret
metadata:
    name: iron-bank
    namespace: gitlab-runner
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDF0amx1WUV5YTgybHhR
            UkRVS3BvVDJmWVZZTmY3UkNyNHZuUUROaWlFCkdVbjRIYWN3Rkp2c3c1SWFadXRN
            djliNXZiTEZsNm1qemdQVEtqbmVWU2cKLS0tIDRoZUFSRW81Tms2WnJtWVgwS0xH
            Q21zcnZNZnBLdE9kUGtXdzlkTjBTMnMK4rJc+oJyid9I1YI/gj7klX1SaWHIDV/7
            yQxYlEQspmCKSg4GbdA/buKic8cALPZDMBg98aNFeaFHs5rbvyjLFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T18:04:49Z"
    mac: ENC[AES256_GCM,data:lWlJDaddyFpS0bRlkcB3uFuUN5P45B/PBMZUG17lx0ovB4Zxlk2O/R3/y17yGV0RGszQgzLThX+Z/NOL5h+fqg1LL3pJ+r8Bto0NoCYQeSiOV4v10X/sT62wRki2m3JTkWjWIMwGr1QstiDxv+B21NEmkzKV85EclpW8FZJ+wXI=,iv:Vtl73b7dGKlrpRdSEhOfcFQ2NeTqs2bKX+YK3so2tfs=,tag:z5PznSkf6H+e4Cg3Z79uKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
