apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:0G4YkZvNzeRgA4+qpQvyMLQK7qnLamxMZl11/NNUT1kuy3xs/r4el5oWI/QBvCjgFPPNtEMbhvAkB+BTrbAQZsOpQx9C9cwCnz6Vp6XbtK4leOHUkYcIt4CC2yqQcBjZvbj8YUq4Gn63mOY0OX64ski7Xoj49PpFQDsqmkFQKeUHgrTad8LcnnvNBmvaHJzttkCZl3x34/jpJjqcrpc1SgCbkOyw7USvqSJQKfAT/Eu7szpqI6qU4iHcYXAR3T1OjGdJ5G80uazzwV3m2HRyEI8e7sVYcgiebkUvXDHqwlOipqextvYT4ViKHCmoJ+HW4GwP3U2qofzKtAbo7ajtdhjSqtvFkeZ7g/KhUmjPoi8=,iv:Oo7nWC64NAPNFJAp7lCqs9SEDnHTVfDzbYuCg7Pdb80=,tag:4b+Ma1FO+oJ8fio0OGbgmQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: private-registry
    namespace: gitlab
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OTFscEFmOTJXS1hhaUFl
            YUQrOUxjelBmeFpxeGFCSExuMThQYS9nWG1jCjdpVXJYYzJaZDloVzJtMURtUENG
            Smo1Tlc0NWIrOGpHSGp4T3haaFFuZ0kKLS0tIFNxWUVlSVEwV0ZLQVZrZkdFcEJD
            dFI2VFdVZnlDQlJpUkpqeFpJeDQrVTAKZwDAP90cuTBtobziQjmFWYuxWibZHcLA
            NAcdNJ5FRuKL9jl+oqTE7a1gnmLC7Bwvk0Zc4UwumWk6wOJtZMjxAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T21:46:11Z"
    mac: ENC[AES256_GCM,data:OHTfo5DY9O+uk8WcEuaosDi6uck8IDaz4w0px9WqKcG0rbQ6slpOlVyC2JgzqTvz8ULndpWmUxwqbFLK7eWQ50d/Soi9x3KZ47bgxLHdhCzIzapdEtH5xuLikj8Cw2DlebZNquX/gamHDgRUoty4fyqnbwp2DipwYaSX5or3IOQ=,iv:1meRaRIzJ1PIdgD/NRK/0R/yBhi8goQLba+DNnQ+sNo=,tag:4oiUmW6Iic4pR7Ng0AIBhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
