apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Xsc+n0KvhFdYqWWiTcKumg==,iv:NJG9G64qdMdYmwNxv4VpgzWW2J/n6ETY/9ulHObRj9I=,tag:idEdKcKuVcixOGej7FkTFw==,type:str]
    username: ENC[AES256_GCM,data:kc0y82Erlg/N/uD0,iv:hUb+FQXLoDTfTv5h6j8+BNZRWjPePV1Zupk/Rc0GYT0=,tag:0c5vEQ40BiaNjbdJFDq6ag==,type:str]
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZDlBUE9KRVhWdTJVSlR2
            YU5xQ1kwOERIcWlzK2wvdERneDBvb0dzTXc4CmgzVVEzbjlGNU9IUGVYU1J2dlJ5
            V0hRRmh3U29VOVAyd0FMZjN0dElEMnMKLS0tIGV0UnUrSEF3NEdaeUdkOUtLWlk2
            YVA5U3RXL3IzOXpyRGNqL0FvSDlkUDgKLiVjOrWKNC4APddBvEfXxw6NZo7okV/h
            a8UYMv4HBiGWQUhWOrIRw09GQssvm9JaOo4UGYhF5YM8FcFbPDcuNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T18:25:13Z"
    mac: ENC[AES256_GCM,data:jlmruVzOft/PSyTiKyRpVHujxSEHA6uQYBy9VisvxWCtxbOBdTu7ZCLlzNpDfqwft4mxJiyorUxHz2lVJIa/OW4QCIa4yfZUTWd82PjvzvaM3+0pTFN6QU4Mm0HQ9mPLsko18AkBj3pVPCuLyFmkywgMRbc6SxZf1lUVvgRo+r4=,iv:VmYcdwisfIcN6KtXnU4rHZyfujuLZJhEbrSk28KXqmY=,tag:0GNkjryRhQmPL8PgwBfRgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-login
    namespace: keycloak
type: Opaque
stringData:
    JAVA_OPTS_APPEND: ENC[AES256_GCM,data:CqUQdVlNWBTqIT4+EWmr8JpoDPqyiPfzIw0zgOjBYNiUC5hA5Q==,iv:eC97rjYqDM3s0d+MoRqKmnhdqP4b4Hl2xEwFzm5F3no=,tag:uT9O8venzYxXBV4dpa/tMg==,type:str]
    JAVA_TOOL_OPTIONS: ENC[AES256_GCM,data:oGJMix0iLlYuMGnckKJkZVH6zKsz2Fc=,iv:RZzPXAvgFRfaTzfdXJTkMYjG5KGAI/NHV+T6orQ9Qwg=,tag:JotePvI/lKXfPlpVEy465w==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:l8OHDtG0thBI,iv:nfW5uxaLNTO0IbMU0S6xq4CpUrf5xI4+U7jhpBUc+W4=,tag:hpB4Eo65RMHc5A2mmvMMRw==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:sfJvf8dz3tdW,iv:YJcmCTh8A7s3rCLP9tKAb/vx/25zGCf/2EXBHdYyFwg=,tag:d+++BaRNjqDLu0zg2W2URg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZDlBUE9KRVhWdTJVSlR2
            YU5xQ1kwOERIcWlzK2wvdERneDBvb0dzTXc4CmgzVVEzbjlGNU9IUGVYU1J2dlJ5
            V0hRRmh3U29VOVAyd0FMZjN0dElEMnMKLS0tIGV0UnUrSEF3NEdaeUdkOUtLWlk2
            YVA5U3RXL3IzOXpyRGNqL0FvSDlkUDgKLiVjOrWKNC4APddBvEfXxw6NZo7okV/h
            a8UYMv4HBiGWQUhWOrIRw09GQssvm9JaOo4UGYhF5YM8FcFbPDcuNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T18:25:13Z"
    mac: ENC[AES256_GCM,data:jlmruVzOft/PSyTiKyRpVHujxSEHA6uQYBy9VisvxWCtxbOBdTu7ZCLlzNpDfqwft4mxJiyorUxHz2lVJIa/OW4QCIa4yfZUTWd82PjvzvaM3+0pTFN6QU4Mm0HQ9mPLsko18AkBj3pVPCuLyFmkywgMRbc6SxZf1lUVvgRo+r4=,iv:VmYcdwisfIcN6KtXnU4rHZyfujuLZJhEbrSk28KXqmY=,tag:0GNkjryRhQmPL8PgwBfRgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
