apiVersion: v1
data:
    password: ENC[AES256_GCM,data:haIitHQhG21sCDjVkYrIqQ==,iv:E0O5Q1U2SzGu8zBPw7n72L7CJo60wl1CsdZeTAJ74BA=,tag:iTHRmFkN3zS9gDbSTbcz9A==,type:str]
    username: ENC[AES256_GCM,data:1UpJJFRtXWiu/2y6,iv:EuE8KGDzVEzcOLiVBjgBKDIclrZDnWQcL0vtAFaVYfU=,tag:BlZcJzU57wS2RRS0cpoJlA==,type:str]
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YkxLbE5TL1Q0WHJNek5X
            TWMyTnU1aTh2bEhma2pramxrQWVUazRjQW1nClZIRFUwRDdBSi9VUHFkVzhUeXdu
            N2UrblhCUU1salVFbVd1TE9NQU9nT1UKLS0tIHNXemNUZVpPWTNXbVh1NWhIZURI
            K0VIVVdVWC9lUkJxVnQ3dFU2cy9USzQKTSdPnErsNuifuFjl1BYJdv9e823oc7Aa
            /97uKJohQyS/ConhvWWPjo9IiDO2AJCO6rJc9zuB59jh6rNYpCOABw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T20:19:07Z"
    mac: ENC[AES256_GCM,data:0KvWku2icIixwa3sBUt85vZE7hkUaDX8g+p+NpF+DcGSCBUxXmqHaYYZGdOAG9hAPtMpcb49D3FDAt5QyxeLznhB2khKXNUtiN9LXNK4YiNIrJUGHOIc8fFINn/JI4PFu9gbQJJ6Om38LolocVrT+dwfxsDXgUh1/mtWs3bDo6o=,iv:MNTJibbptZZfr97fSG4rDvuzLY/LdiqmBIq1GrwFP84=,tag:iuq9SquC/RDY5I9XE93zQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-login
    namespace: keycloak
type: Opaque
stringData:
    JAVA_OPTS_APPEND: ENC[AES256_GCM,data:flISjcm/4AbTp3XbDdpTrxblShTLvSIgnD1UWKSs269QC86W1gpDVC2FHUiHrM21Eg==,iv:FVv6reuoCiKDxpewxpt6B4Tn33kIE4JSa2gTtVO6CYw=,tag:CMINqlo3ivJnE9RCQcFwsQ==,type:str]
    JAVA_TOOL_OPTIONS: ENC[AES256_GCM,data:VfotlRaX/t6vdQftmccKAmtMEKxC/4k=,iv:NXfgIA+yz0WypvMUimtV5fyQ3WYjBtANT4FMvS/5WJg=,tag:WM1L0mbFBcUPoV9pSnWnwg==,type:str]
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:0MAvwdDzQqJA,iv:G/T9tB059U+lINAC0qbS1q+wNS9ferz5nYismg4n1KA=,tag:1JRBe3/omVxCH2MZrwAacA==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:wyXhUAAz82iM,iv:faFzEol0PYCNtc0ENks7BR1taF2JXKSHVA6xVBOTSts=,tag:hDMNuAj8zBZMJvEpT+TOkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YkxLbE5TL1Q0WHJNek5X
            TWMyTnU1aTh2bEhma2pramxrQWVUazRjQW1nClZIRFUwRDdBSi9VUHFkVzhUeXdu
            N2UrblhCUU1salVFbVd1TE9NQU9nT1UKLS0tIHNXemNUZVpPWTNXbVh1NWhIZURI
            K0VIVVdVWC9lUkJxVnQ3dFU2cy9USzQKTSdPnErsNuifuFjl1BYJdv9e823oc7Aa
            /97uKJohQyS/ConhvWWPjo9IiDO2AJCO6rJc9zuB59jh6rNYpCOABw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T20:19:07Z"
    mac: ENC[AES256_GCM,data:0KvWku2icIixwa3sBUt85vZE7hkUaDX8g+p+NpF+DcGSCBUxXmqHaYYZGdOAG9hAPtMpcb49D3FDAt5QyxeLznhB2khKXNUtiN9LXNK4YiNIrJUGHOIc8fFINn/JI4PFu9gbQJJ6Om38LolocVrT+dwfxsDXgUh1/mtWs3bDo6o=,iv:MNTJibbptZZfr97fSG4rDvuzLY/LdiqmBIq1GrwFP84=,tag:iuq9SquC/RDY5I9XE93zQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
