apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
   - secret.sops.yaml
   - keycloak-database-enc.yaml 
   - tls-secret-enc.yaml 
   - my-secrets.yaml
   - keycloak-admin-enc.yaml
   - keycloak-tls.yaml
   - kms-secret-enc.yaml