apiVersion: v1
data:
    jdbc-password: ENC[AES256_GCM,data:s9pv9RjSnkaCIP8pjVyqsmGmIRxpPmoVHcMDbmwC6688Dms0Mxh6uQ==,iv:sV3ac542XzeGx3gcqrGa2/t7iqUHWU5vCj1ALfm2fuA=,tag:IbKX5sYSVfLrNSX2CXkRqg==,type:str]
kind: Secret
metadata:
    name: sonarqube-db
    namespace: sonarqube
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQW1pc3VVQ1JnT3NDNDJT
            QjRRa1dCTm9uQWcrclJlSDB4VzVZaVNDREdnClZlTnhwTzZ1NlFxOWZEaUNZcElW
            bkcxK0pzTnV2NFk3eFZBdWxWOExNK3cKLS0tIFYyNURic21Xc0NEcmgvWFJJdVZ3
            K1M1Yno0WXNuMWJZODhVUi8rdUhrKzQK7oEMjtKd7GVflMVBlE3P7w+sGFh4sSi/
            /fkZcbjuYDWQIb5EMo54q/nbm16Ppkfr/9v6MjkR+CinLLPcKEki1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-01T16:21:04Z"
    mac: ENC[AES256_GCM,data:SxPOgrdtbgHGeVcDLT9NHAmuxUuqGHT2dW818dDsTqYuH6FddXLdutitMRoTlOr9yE/vSsdz1/CkZ+zj+u7bjqFv3oYWR/hvO97S2TqDlist08d3MGrEMsFpjDaDpISN2NSG7IFfjM8Uq2s+uYOSAtxAOd60V3CTp5mVJHoegRQ=,iv:C0m4AjqMDjlqGFNRP/EtqR0oXuD9GP3xmtqQy0VbxZU=,tag:w9Y+Km3UQ2KkpFPKpUGvxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
