apiVersion: v1
data:
    aws: ENC[AES256_GCM,data:BfNluVC/4ruYywEGVPiAypDOJfZKLIj47q+zaWB6II5h8mop5hudoxzmLvc7fgEHud7vwb31IRdbBmKsbsUveVEjUeyZp/NhY06GxYPY7mpL7yHJWksk9MSsnsJbvJlvL87PjgLs6Gqa20bFdfB6ovJs8G5KsMOKzRuyeDDeieOOfR24jl5Sor0P1GAFYo+5NzEpzVTzOSHvGa6y,iv:UZ0vHetVBJpKQJYTLGcvx5saWQbd1XKqNmsiSzw2h40=,tag:aSvNhCjMcaEYXXtACVOA+Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: aws-auth
    namespace: velero
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1emVWRVhIcUEra3MwY2JU
            a1R5cDNBanc5bVB6Ym5WNDRIMmVvYkowbjNzCnZlVmMvNzhnWk9JRDl0TmxRVy95
            NEdKL0NwMnRVRzYvNXcxL2VJeWh5OVUKLS0tIENGeGk0bFhoWjhXZGRXeXpOZW0z
            M2dkTEhkbmNwMThHR3Izb2c2bmMvZUUK+nUgP64jW047KnIHqmtDA3DtfkLdfDCB
            Wf6nTqysZs0+Yfv88C/yBx/3JP/9A+tb6oqY5x8lNViztXhskAK61g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-04T09:21:03Z"
    mac: ENC[AES256_GCM,data:P/iiCZxv/4oEj0Gg72cFF917s8G56KJyQxpK4mOW9EK4jTCSQDb3SKcefphZHDsDxVlQvmrmN8gEHknZ7p6KWimqPM6xUX/P2FIceP32yZ+tXjGqW0Z6kc32xqrrpAutFW4rcK+SkaGYBROafhko+Osn0yVYkohRmTPRbwoSN/0=,iv:MyLmter/K6rAvx6SA63RsZ7o94ZVFFPhOpb7Lz7IlnI=,tag:6h9ow2kyFSMM04w7kdFc0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
