
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: semaphore-ansible-semaphore-config
#   namespace: semaphore
#   labels:
#     app.kubernetes.io/name: "ansible-semaphore"
#     app.kubernetes.io/instance: "semaphore"
# data:
#   config.json: |
#     {
#       "ssh_config_path": "~/.ssh/config",
#       "billing_enabled": true
#     }
# ---
# Source: ansible-semaphore/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-ansible-semaphore-workdir
  namespace: semaphore
  labels:
    app.kubernetes.io/name: "ansible-semaphore"
    app.kubernetes.io/instance: "semaphore"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10G"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: semaphore-ansible-semaphore
  namespace: semaphore
---
apiVersion: v1
kind: Service
metadata:
  name: semaphore-ansible-semaphore
  namespace: semaphore
  labels:
    app.kubernetes.io/name: "ansible-semaphore"
    app.kubernetes.io/instance: "semaphore"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ansible-semaphore
    app.kubernetes.io/instance: semaphore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: semaphore-ansible-semaphore
  namespace: semaphore
  labels:
    app.kubernetes.io/name: "ansible-semaphore"
    app.kubernetes.io/instance: "semaphore"
spec:
  serviceName: semaphore-ansible-semaphore
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ansible-semaphore
      app.kubernetes.io/instance: semaphore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ansible-semaphore"
        app.kubernetes.io/instance: "semaphore"
    spec:
      serviceAccountName: semaphore-ansible-semaphore
      securityContext:
        fsGroup: 1001
      containers:
        - name: ansible-semaphore
          image: semaphoreui/semaphore:v2.9.37
          env:
            - name: SEMAPHORE_PORT
              value: "3000"
            - name: SEMAPHORE_GIT_CLIENT
              value: "cmd_git"
            - name: SEMAPHORE_TMP_PATH
              value: "/tmp/semaphore"
            - name: SEMAPHORE_MAX_PARALLEL_TASKS
              value: "0"
            - name: SEMAPHORE_PASSWORD_LOGIN_DISABLED
              value: "false"
            - name: SEMAPHORE_NON_ADMIN_CAN_CREATE_PROJECT
              value: "false"
            - name: SEMAPHORE_USE_REMOTE_RUNNER
              value: "false"
            - name: SEMAPHORE_DB_DIALECT
              value: "postgres"
            - name: SEMAPHORE_DB_HOST
              value: "dbms.fredgentech.net"
            - name: SEMAPHORE_DB_PORT
              value: "5432"
            - name: SEMAPHORE_DB
              value: "semaphore"
            - name: SEMAPHORE_DB_USER
              value: "databaseadmin"
            - name: SEMAPHORE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: semaphore-ansible-semaphore-database
                  key: password
            - name: SEMAPHORE_LDAP_ENABLE
              value: "false"
            - name: SEMAPHORE_EMAIL_ALERT
              value: "false"
            - name: SEMAPHORE_TELEGRAM_ALERT
              value: "false"
            - name: SEMAPHORE_SLACK_ALERT
              value: "false"
            - name: SEMAPHORE_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: semaphore-ansible-semaphore-runner
                  key: token
            - name: SEMAPHORE_COOKIE_HASH
              valueFrom:
                secretKeyRef:
                  name: semaphore-ansible-semaphore-general
                  key: cookieHash
            - name: SEMAPHORE_COOKIE_ENCRYPTION
              valueFrom:
                secretKeyRef:
                  name: semaphore-ansible-semaphore-general
                  key: cookieEncryption
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              valueFrom:
                secretKeyRef:
                  name: semaphore-ansible-semaphore-general
                  key: accesskeyEncryption
# Additional envs
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: "blablabla"
            - name: SEMAPHORE_ADMIN_NAME
              value:  "admin"
            - name: SEMAPHORE_ADMIN_EMAIL
              value:  "admin@localhost"
            - name: SEMAPHORE_ADMIN
              value:  "admin"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits: {}
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /etc/semaphore/config.json
              subPath: config.json
            - name: workdir
              mountPath: /tmp/semaphore
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: semaphore-config
              items:
                - key: config.json
                  path: config.json
      # - name: config
      #   configMap:
      #     name: semaphore-ansible-semaphore-config
      # - name: workdir
        persistentVolumeClaim:
          claimName: semaphore-ansible-semaphore-workdir
---
apiVersion: v1
kind: Pod
metadata:
  name: "semaphore-ansible-semaphore-test-connection"
  labels:
    app.kubernetes.io/name: "ansible-semaphore"
    app.kubernetes.io/instance: "semaphore"
spec:
  restartPolicy: Never
  imagePullSecrets:
      - name: private-registry
  containers:
    - name: wget
      image: ghcr.io/asongent/busybox:latest  
      command:
        - wget
      args:
        - --spider
        - http://semaphore-ansible-semaphore:3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: semaphore-vs
  namespace: semaphore
spec:
  gateways:
  - istio-system/general-gateway
  hosts:
  - 'semaphore.stack.fredgentech.net'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: semaphore-ansible-semaphore
        port:
          number: 3000